### ISSUE TITLE
Doesn't work in browser

### ISSUE THREAD

**Issue by TheLucifurry** [Namide/extract-colors#25]
Bundler: Vite@3.1.8
"extract-colors" version: 1.1.22

It's trying to import canvas package, which it shouldn't do

![image](https://user-images.githubusercontent.com/47812547/197387406-7ee94d58-81d8-4126-9156-8abdb8e52e7f.png)

**Comment by Namide** [comment]
Hello @TheLucifurry,

The `canvas` dependency is only needed in the Node.js environment.
If you are using extract colors in the browser, do not add the `canvas` dependency.

If you do not has import canvas, your bundler use a bad module : this lib contain 3 modules formats (ES, CSJ, UMD).
If you can force the UMD module it will be better.

If the error persists, please send me your configuration and an exemple to reproduce this error (I see Vite and pnpm, I never tried this combo).

**Comment by Namide** [comment]
Hello @TheLucifurry,

I've update to version `1.1.23` without the nodeJS esm module. This will solve your problem.

To update your dependency use the command:

```bash
npm r extract-colors; npm i extract-colors@"<2.0.0"
```

If you need to force the esm module, you can follow the new documentation:
```js
import extractColors from 'extract-colors/dist/extract-colors.browser.es.js'

const src = 'my-image.jpg'

extractColors(src)
  .then(console.log)
  .catch(console.error)
```

I'm closing this issue, if your error persist, please reopen it
