### ISSUE TITLE
How can I use the library with React JS?

### ISSUE THREAD

**Issue by quocbahuynh** [Namide/extract-colors#27]
I get an error when trying to using React

**Comment by Namide** [comment]
Hello @quocbahuynh,

Do you have an example to reproduce this issue please?
A `codepen.io` maybe.

**Comment by Namide** [comment]
Hello @quocbahuynh,

This issue seems to be the same: https://github.com/Namide/extract-colors/issues/28
Can you try to upgrade to the new release `2.0.3`.
Does that solve your problem?
