### ISSUE TITLE
React.js + TypeScript issue(s) 

### ISSUE THREAD

**Issue by cyberpoetry17** [Namide/extract-colors#28]
Hello,
Issue(s) I've encountered after installing library are:
1.)  'This expression is not callable. Type 'type of import(..../extract-colors/index)' has no call signatures' when trying to import and use extractColors for browser (React.js + Typescript):
![image](https://user-images.githubusercontent.com/44535341/205004279-3cd6d05c-83d3-4433-94be-a687214f45d9.png)

2.) I've tried importing and using extractColorsFromSrc which somehow returns a promise. While trying to resolve it 'Property 'then' does not exist on type 'Colors[]'' and 'Unsafe call of an 'any' typed value' messages show. :space_invader: :space_invader: :space_invader:

I see that the package has typescript types provided by https://www.npmjs.com/package/@types/extract-colors

Thanks for time and help!

**Comment by Namide** [comment]
Hello @cyberpoetry17,

Thanks to use my lib 
The types from https://www.npmjs.com/package/@types/extract-colors does indeed have errors.
I rebuilt the whole library in Typescript to support types directly in the package.
You can upgrade to the new release `2.0.3`.
This should solve the problems.

**Comment by cyberpoetry17** [comment]
It works like magic :sparkles:, thank you very very much!
