### ISSUE TITLE
Webpack errors

### ISSUE THREAD

**Issue by eagleeyejack** [Namide/extract-colors#31]
Hello friend, just to let you know I had to downgrade to 2.0.3 (from 2.0.4) to get this working in React 18, you may already be aware of this.

Once I did this it worked, feel free to close if not relevant! thanks for the package!

**Comment by Namide** [comment]
Hello @eagleeyejack,

Thank you for your feedback, it will help me improve `extract-colors`.

I've just try to compile with React and Webpack with the `2.0.4` version of `extract-colors`.
Indeed the default import does not work.

It working with the destructuring assignment:

```jsx
import React from "react";
// import extractColors from "extract-colors"; // not working
import { extractColors } from "extract-colors"; // working

class Colors extends React.Component {
  constructor(props) {
    super(props);
    this.state = { colors: "Loading" };
  }

  render() {
    const src = "/img.svg";

    extractColors(src)
      .then((data) => {
        this.setState({
          colors: data.map(({ hex }) => hex).join(" ")
        });
      })
      .catch(console.error);

    return (
      <div>
        <p>Colors</p>
        <p>{this.state.colors}</p>
      </div>
    );
  }
}

export default Colors;
```

[Here my full test](https://codesandbox.io/s/react-webpack-demo-forked-1hyuuf?file=/src/Colors.jsx)

I'll try to fix it soon, I'll let you know in this ticket.

**Comment by Namide** [comment]
Finally I've remove the default import from documentation to avoid errors.
If you still encounter an error, don't hesitate to let me know.
Otherwise I will close this ticket.
