### ISSUE TITLE
Issue with the source map in v4.0.3

### ISSUE THREAD

**Issue by himanshu-satija** [Namide/extract-colors#44]
Using the package in a vite project breaks because of source maps in version 4.0.3

![image](https://github.com/Namide/extract-colors/assets/15103616/b6144f46-29a6-4304-ab82-3bf138a5ec7f)

This can be reproduced by simply creating a new vite project `yarn create vite extract-colors-test --template vanilla`, installing extract-colors and importing extractColors function.

**Comment by Namide** [comment]
Thanks for your ticket and your explanations @himanshu-satija 

I've just fix this source maps bug with a new `v4.0.4`:
- https://github.com/Namide/extract-colors/releases/tag/v4.0.4
- https://www.npmjs.com/package/extract-colors/v/4.0.4

Can you remove the last version of your project and replace by the new?
Does this new version work well for you?

**Comment by himanshu-satija** [comment]
Works fine with 4.0.4. Thanks for the super quick fix @Namide 🙏
