### ISSUE TITLE
about node.js example code in readme

### ISSUE THREAD

**Issue by YellaGoya** [Namide/extract-colors#45]
hello!
First of all, I'm using the library really well. 
Thank you for your hard work.

I was looking at the node.js examples in the current readme and I have a question, so I'm writing an issue.

In it, we use the getPixels library to get the data of an image.
`const width = Math.round(Math.sqrt(data.length / 4));`
`const height = width;`
The current readme file shows an example like the one above.

The imageData object requires data, width, and height.
I think that width and height should be the actual pixels of the image.

However, if we use sqrt of total pixels / 4, then using an image with a resolution of 500 * 335, we get 409 horizontal pixels, which is quite far from the actual 500.
We're using the same height as width here, which also makes a difference.

I'm wondering if using different widths and heights won't cause too much of a problem for the library to extract the actual color.

When using getPixels, pixel.shape holds an array of [width, height, channel], so I thought it would be nice to modify the readme file to say something like this

```
const path = require('path')
const getPixels = require("get-pixels")
const { extractColors } = require('extract-colors')

const src = path.join(__dirname, './my-image.jpg')

getPixels(src, (err, pixels) => {
  if(!err) {
    const data = [...pixels.data]
    const width = pixels.shape[0];
    const height = pixels.shape[1];

    extractColors({ data, width, height })
      .then(console.log)
      .catch(console.log)
  }
})
```

Thank you for reading.

**Comment by Namide** [comment]
Hello @YellaGoya,

Thank's for this feedback, it will help me to improve extract-colors 🙏

To answer your questions: 

> The imageData object requires data, width, and height.  
> I think that width and height should be the actual pixels of the image.  
> However, if we use sqrt of total pixels / 4, then using an image with a resolution of 500 * 335, we get 409 horizontal pixels, which is quite far from the actual 500.  
> We're using the same height as width here, which also makes a difference.

Yes, you're right


> I'm wondering if using different widths and heights won't cause too much of a problem for the library to extract the actual color.

Size is used to optimize the calculation by “skipping” pixels. The final result should not vary greatly, because the “skipped” pixels are distributed throughout the image. It's as if you'd reduced it slightly before starting the calculation.

> When using getPixels, pixel.shape holds an array of [width, height, channel], so I thought it would be nice to modify the readme file to say something like this

Yes, you're right, I've just updated the documentation 👍️

---

Thanks for your help.  
Everything looks good to you now?

**Comment by YellaGoya** [comment]
Thank you for your feedback.
I'm really enjoying using the library. It's awesome!

**Comment by Namide** [comment]
Thanks for your feedback and help @YellaGoya 🙂
Glad this library is useful
